language: cpp
before_script:
  - sudo apt-get install libboost-test-dev -y
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
compiler: clang
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uflanker-d:$BINTRAY_API_KEY "https://api.bintray.com/content/flankerd/otuscpp/03_allocator/$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  
